# conf/cifar_resnet18.yaml

dataset:
  _target_: src.dataset_factory.get_dataset
  name: cifar10
  num_clients: 5
  partition:
    strategy: dirichlet
    alpha: 0.75
  root: /tmp/data

model:
  _target_: src.model_factory.get_model
  arch: resnet18
  num_classes: 10

algorithm:
  _target_: src.algorithm_factory.get_fl_algo
  name: fedavg
  local_epochs: 5
  lr: 0.01
  client_fraction: 1.0

task:
  num_classes: 10
  loss:
    _target_: torch.nn.CrossEntropyLoss
  metrics:
    top1:
      _target_: src.metrics.top1_accuracy  # or omit if not used