debug: True
dataset:
  _target_: src.dataset_factory.get_dataset
  name: mnist
  num_clients: 2
  alpha: 1000
  root: /tmp/data

dataloader:
  num_workers: 2
  pin_memory: False
  batch_size: 64

algorithm:
  _target_: src.algorithm_factory.get_fl_algo
  name: fedavgm
  local_epochs: 1
  lr: 0.01
  mu: 0.01        # Only for fedprox
  eta: 0.001      # Only for fedadam
  momentum: 0.9   # Only for fedavgm
  client_fraction: 0.1

task:
  num_of_rounds: 2

backend_config:
  client_resources:
    num_cpus: 1     # each client may use up to 8 CPU cores
    num_gpus: 0     # Leave it to zero if you have no cpus

trainer:
  accelerator: auto
  precision:   16-mixed
