debug: False
dataset:
  _target_: src.dataset_factory.get_dataset
  name: mnist
  num_clients: 10
  alpha: 1
  root: /tmp/data

dataloader:
  num_workers: 16
  pin_memory: True
  batch_size: 64


algorithm:
  _target_: src.algorithm_factory.get_fl_algo
  name: fedavg
  local_epochs: 5
  lr: 1e-3
  client_fraction: 0.4

task:
  num_of_rounds: 1000

backend_config:
  client_resources:
    num_cpus: 2     # each client may use up to 8 CPU cores
    num_gpus: 0.10  # each client may use 10% of a single GPU’s VRAM



trainer:
  accelerator: auto
  precision:   16-mixed
